# Generated by Django 4.1.5 on 2025-02-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rmse', models.FloatField()),
                ('nrmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('mbe', models.FloatField()),
                ('r2_coefficient', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ANN',
            },
        ),
        migrations.CreateModel(
            name='manage_users_model',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_Profile', models.FileField(upload_to='images/')),
                ('User_Email', models.EmailField(max_length=50)),
                ('User_Status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'manage_users',
            },
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rmse', models.FloatField()),
                ('nrmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('mbe', models.FloatField()),
                ('r2_coefficient', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SVM',
            },
        ),
    ]
